# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  run-tests:
    docker: &test_and_postgres
      - image: michaelkaminsky/dbt-helper
      - image: postgres
        name: database
        environment: &pgenv
          POSTGRES_USER: "root"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "dbt"
    steps:
      - checkout
      - run: &setupdb
          name: Setup postgres
          command: bash test/setup_db.sh
          environment:
            PGHOST: database
            PGUSER: root
            PGPASSWORD: password
            PGDATABASE: postgres
      - run: tox
  build-and-deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: 
          name: create packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install wheel
            pip install twine
            python setup.py verify
            python setup.py sdist
            python setup.py bdist_wheel
      - run: 
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = turingmachin" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  untagged-build:
    jobs:
      - run-tests
  build-and-deploy:
    jobs:
      - run-tests:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - build-and-deploy:
          requires:
            - run-tests
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
